[24-Dec-2013 21:51:48 Europe/Zagreb] PHP Fatal error:  Uncaught exception 'Exception' with message 'Class does not exist : MysqlPreparedStatementsTestCase
' in /home/eval/framework/base/TestUnitModule.php:235
Stack trace:
#0 /home/eval/framework/base/TestUnitModule.php(268): TestUnitModule::runAllTestsOnTestModule('MysqlPreparedSt...')
#1 /home/eval/framework/tools/testrun.php(7): TestUnitModule::run(Array)
#2 {main}
  thrown in /home/eval/framework/base/TestUnitModule.php on line 235
[24-Dec-2013 21:53:43 Europe/Zagreb] PHP Fatal error:  Uncaught exception 'Exception' with message 'Class does not exist : MysqlPreparedStatementsTestCase
' in /home/eval/framework/base/TestUnitModule.php:235
Stack trace:
#0 /home/eval/framework/base/TestUnitModule.php(268): TestUnitModule::runAllTestsOnTestModule('MysqlPreparedSt...')
#1 /home/eval/framework/tools/testrun.php(7): TestUnitModule::run(Array)
#2 {main}
  thrown in /home/eval/framework/base/TestUnitModule.php on line 235
[24-Dec-2013 21:53:45 Europe/Zagreb] PHP Fatal error:  Uncaught exception 'Exception' with message 'Class does not exist : MysqlPreparedStatementsTestCase
' in /home/eval/framework/base/TestUnitModule.php:235
Stack trace:
#0 /home/eval/framework/base/TestUnitModule.php(268): TestUnitModule::runAllTestsOnTestModule('MysqlPreparedSt...')
#1 /home/eval/framework/tools/testrun.php(7): TestUnitModule::run(Array)
#2 {main}
  thrown in /home/eval/framework/base/TestUnitModule.php on line 235
[24-Dec-2013 21:54:03 Europe/Zagreb] PHP Fatal error:  Uncaught exception 'Exception' with message 'Class does not exist : MysqlPreparedStatementsTestCase
' in /home/eval/framework/base/TestUnitModule.php:235
Stack trace:
#0 /home/eval/framework/base/TestUnitModule.php(268): TestUnitModule::runAllTestsOnTestModule('MysqlPreparedSt...')
#1 /home/eval/framework/tools/testrun.php(7): TestUnitModule::run(Array)
#2 {main}
  thrown in /home/eval/framework/base/TestUnitModule.php on line 235
[24-Dec-2013 21:54:48 Europe/Zagreb] PHP Fatal error:  Uncaught exception 'Exception' with message 'Class does not exist : MysqlPreparedStatementsTestCase
' in /home/eval/framework/base/TestUnitModule.php:235
Stack trace:
#0 /home/eval/framework/base/TestUnitModule.php(268): TestUnitModule::runAllTestsOnTestModule('MysqlPreparedSt...')
#1 /home/eval/framework/tools/testrun.php(7): TestUnitModule::run(Array)
#2 {main}
  thrown in /home/eval/framework/base/TestUnitModule.php on line 235
[24-Dec-2013 21:54:48 Europe/Zagreb] PHP Fatal error:  Uncaught exception 'Exception' with message 'Class does not exist : MysqlPreparedStatementsTestCase
' in /home/eval/framework/base/TestUnitModule.php:235
Stack trace:
#0 /home/eval/framework/base/TestUnitModule.php(268): TestUnitModule::runAllTestsOnTestModule('MysqlPreparedSt...')
#1 /home/eval/framework/tools/testrun.php(7): TestUnitModule::run(Array)
#2 {main}
  thrown in /home/eval/framework/base/TestUnitModule.php on line 235
[24-Dec-2013 21:55:26 Europe/Zagreb] PHP Fatal error:  Uncaught exception 'Exception' with message 'Class does not exist : MysqlPreparedStatementsTestCase' in /home/eval/framework/base/TestUnitModule.php:235
Stack trace:
#0 /home/eval/framework/base/TestUnitModule.php(268): TestUnitModule::runAllTestsOnTestModule('MysqlPreparedSt...')
#1 /home/eval/framework/tools/testrun.php(7): TestUnitModule::run(Array)
#2 {main}
  thrown in /home/eval/framework/base/TestUnitModule.php on line 235
[24-Dec-2013 21:55:53 Europe/Zagreb] PHP Fatal error:  Uncaught exception 'Exception' with message 'Class does not exist : MysqlPreparedStatementsTestCase' in /home/eval/framework/base/TestUnitModule.php:235
Stack trace:
#0 /home/eval/framework/base/TestUnitModule.php(268): TestUnitModule::runAllTestsOnTestModule('MysqlPreparedSt...')
#1 /home/eval/framework/tools/testrun.php(7): TestUnitModule::run(Array)
#2 {main}
  thrown in /home/eval/framework/base/TestUnitModule.php on line 235
[24-Dec-2013 21:56:08 Europe/Zagreb] PHP Fatal error:  Uncaught exception 'Exception' with message 'Class does not exist : MysqlPreparedStatementsTestCase' in /home/eval/framework/base/TestUnitModule.php:235
Stack trace:
#0 /home/eval/framework/base/TestUnitModule.php(268): TestUnitModule::runAllTestsOnTestModule('MysqlPreparedSt...')
#1 /home/eval/framework/tools/testrun.php(7): TestUnitModule::run(Array)
#2 {main}
  thrown in /home/eval/framework/base/TestUnitModule.php on line 235
[24-Dec-2013 21:56:28 Europe/Zagreb] PHP Fatal error:  Uncaught exception 'Exception' with message 'Class does not exist : MysqlPreparedStatementsTestCase' in /home/eval/framework/base/TestUnitModule.php:235
Stack trace:
#0 /home/eval/framework/base/TestUnitModule.php(268): TestUnitModule::runAllTestsOnTestModule('MysqlPreparedSt...')
#1 /home/eval/framework/tools/testrun.php(7): TestUnitModule::run(Array)
#2 {main}
  thrown in /home/eval/framework/base/TestUnitModule.php on line 235
[24-Dec-2013 21:57:06 Europe/Zagreb] PHP Fatal error:  Uncaught exception 'Exception' with message 'Assert Equal failed for array (
  'expected' => 
  array (
    0 => 'article',
  ),
  'measured' => 
  array (
    0 => 'article',
    1 => 'temp_table',
  ),
)' in /home/eval/framework/base/TestUnitModule.php:191
Stack trace:
#0 /home/eval/framework/dataprovider/testsuite/MysqlPreparedStatementsTestCase.php(43): TestUnitModule->assertEqual(Array, Array)
#1 /home/eval/framework/dataprovider/testsuite/MysqlPreparedStatementsTestCase.php(12): MysqlPreparedStatementsTestCase->createTables()
#2 /home/eval/framework/base/TestUnitModule.php(230): MysqlPreparedStatementsTestCase->__construct()
#3 /home/eval/framework/base/TestUnitModule.php(268): TestUnitModule::runAllTestsOnTestModule('MysqlPreparedSt...')
#4 /home/eval/framework/tools/testrun.php(7): TestUnitModule::run(Array)
#5 {main}
  thrown in /home/eval/framework/base/TestUnitModule.php on line 191
[24-Dec-2013 21:57:47 Europe/Zagreb] PHP Fatal error:  Uncaught exception 'Exception' with message 'Assert Equal failed for array (
  'expected' => 
  array (
  ),
  'measured' => 
  array (
    0 => 'temp_table',
  ),
)' in /home/eval/framework/base/TestUnitModule.php:191
Stack trace:
#0 /home/eval/framework/dataprovider/testsuite/MysqlPreparedStatementsTestCase.php(30): TestUnitModule->assertEqual(Array, Array)
#1 /home/eval/framework/dataprovider/testsuite/MysqlPreparedStatementsTestCase.php(19): MysqlPreparedStatementsTestCase->dropAll()
#2 /home/eval/framework/base/TestUnitModule.php(139): MysqlPreparedStatementsTestCase->__destruct()
#3 /home/eval/framework/base/TestUnitModule.php(231): TestUnitModule->start()
#4 /home/eval/framework/base/TestUnitModule.php(268): TestUnitModule::runAllTestsOnTestModule('MysqlPreparedSt...')
#5 /home/eval/framework/tools/testrun.php(7): TestUnitModule::run(Array)
#6 {main}

Next exception 'Exception' with message 'Assert Equal failed for array (
  'expected' => 
  array (
  ),
  'measured' => 
  array (
    0 => 'temp_table' in /home/eval/framework/base/TestUnitModule.php on line 191
[24-Dec-2013 21:58:12 Europe/Zagreb] PHP Fatal error:  Uncaught exception 'Exception' with message 'Assert Equal failed for array (
  'expected' => 
  array (
    0 => 
    array (
      'title' => 'Duplicate',
      'created' => '2013-12-24 19:00:00',
    ),
    1 => 
    array (
      'title' => 'Duplicate',
      'created' => '2013-12-24 19:00:00',
    ),
  ),
  'measured' => 
  array (
  ),
)' in /home/eval/framework/base/TestUnitModule.php:191
Stack trace:
#0 /home/eval/framework/dataprovider/testsuite/MysqlPreparedStatementsTestCase.php(110): TestUnitModule->assertEqual(Array, Array)
#1 [internal function]: MysqlPreparedStatementsTestCase->preparedStatement_integerArgs_array()
#2 /home/eval/framework/base/TestUnitModule.php(98): call_user_func(Array)
#3 /home/eval/framework/base/TestUnitModule.php(231): TestUnitModule->start()
#4 /home/eval/framework/base/TestUnitModule.php(268): TestUnitModule::runAllTestsOnTestModule('MysqlPreparedSt...')
#5 /home/eval/framework/tools/testrun.php(7): TestUnitModule::run(Array)
#6 {main}
  thrown in /home/eval/framework/base/TestUnitModule.php on line 191
[24-Dec-2013 21:58:26 Europe/Zagreb] PHP Fatal error:  Uncaught exception 'Exception' with message 'Assert Equal failed for array (
  'expected' => 
  array (
    4 => 'Duplicate',
    5 => 'Duplicate',
  ),
  'measured' => 
  array (
  ),
)' in /home/eval/framework/base/TestUnitModule.php:191
Stack trace:
#0 /home/eval/framework/dataprovider/testsuite/MysqlPreparedStatementsTestCase.php(210): TestUnitModule->assertEqual(Array, Array)
#1 [internal function]: MysqlPreparedStatementsTestCase->preparedStatement_integerArgs_pairMap()
#2 /home/eval/framework/base/TestUnitModule.php(98): call_user_func(Array)
#3 /home/eval/framework/base/TestUnitModule.php(231): TestUnitModule->start()
#4 /home/eval/framework/base/TestUnitModule.php(268): TestUnitModule::runAllTestsOnTestModule('MysqlPreparedSt...')
#5 /home/eval/framework/tools/testrun.php(7): TestUnitModule::run(Array)
#6 {main}
  thrown in /home/eval/framework/base/TestUnitModule.php on line 191
[24-Dec-2013 21:58:30 Europe/Zagreb] PHP Fatal error:  Uncaught exception 'Exception' with message 'Assert Equal failed for array (
  'expected' => 
  array (
    0 => 
    array (
      'title' => 'Duplicate',
      'created' => '2013-12-24 19:00:00',
    ),
    1 => 
    array (
      'title' => 'Duplicate',
      'created' => '2013-12-24 19:00:00',
    ),
  ),
  'measured' => 
  array (
  ),
)' in /home/eval/framework/base/TestUnitModule.php:191
Stack trace:
#0 /home/eval/framework/dataprovider/testsuite/MysqlPreparedStatementsTestCase.php(110): TestUnitModule->assertEqual(Array, Array)
#1 [internal function]: MysqlPreparedStatementsTestCase->preparedStatement_integerArgs_array()
#2 /home/eval/framework/base/TestUnitModule.php(98): call_user_func(Array)
#3 /home/eval/framework/base/TestUnitModule.php(231): TestUnitModule->start()
#4 /home/eval/framework/base/TestUnitModule.php(268): TestUnitModule::runAllTestsOnTestModule('MysqlPreparedSt...')
#5 /home/eval/framework/tools/testrun.php(7): TestUnitModule::run(Array)
#6 {main}
  thrown in /home/eval/framework/base/TestUnitModule.php on line 191
[24-Dec-2013 22:03:13 Europe/Zagreb] PHP Fatal error:  Uncaught exception 'Exception' with message 'Assert Equal failed for array (
  0 => false,
  1 => 'tbl_30a77e9a9729e17444ddce9bd8057019',
)' in /home/eval/framework/base/TestModule.php:223
Stack trace:
#0 /home/eval/framework/dataprovider/testsuite/MySQLProviderTestModule.php(547): TestModule->assertEquality(false, 'tbl_30a77e9a972...', true)
#1 [internal function]: MySQLProviderTestModule->testDrop()
#2 /home/eval/framework/base/TestModule.php(136): call_user_func(Array)
#3 /home/eval/framework/base/TestUnitModule.php(231): TestModule->start()
#4 /home/eval/framework/base/TestUnitModule.php(268): TestUnitModule::runAllTestsOnTestModule('MySQLProviderTe...')
#5 /home/eval/framework/tools/testrun.php(7): TestUnitModule::run(Array)
#6 {main}
  thrown in /home/eval/framework/base/TestModule.php on line 223
[24-Dec-2013 22:03:27 Europe/Zagreb] PHP Fatal error:  Uncaught exception 'Exception' with message 'Assert Equal failed for array (
  0 => 
  array (
    0 => 'id',
    1 => 'val',
  ),
  1 => 
  array (
    0 => 
    array (
      'Field' => 'id',
      'Type' => 'int(4) unsigned',
      'Collation' => NULL,
      'Null' => 'NO',
      'Key' => 'PRI',
      'Default' => NULL,
      'Extra' => 'auto_increment',
      'Privileges' => 'select,insert,update,references',
      'Comment' => '',
    ),
    1 => 
    array (
      'Field' => 'val',
      'Type' => 'int(4) unsigned',
      'Collation' => NULL,
      'Null' => 'NO',
      'Key' => '',
      'Default' => NULL,
      'Extra' => '',
      'Privileges' => 'select,insert,update,references',
      'Comment' => '',
    ),
  ),
)' in /home/eval/framework/base/TestModule.php:223
Stack trace:
#0 /home/eval/framework/dataprovider/testsuite/MySQLProviderTestModule.php(524): TestModule->assertEquality(Array, Array)
#1 [internal function]: MySQLProviderTestModule->testGetFieldDetails()
#2 /home/eval/framework/base/Test in /home/eval/framework/base/TestModule.php on line 223
[24-Dec-2013 22:04:55 Europe/Zagreb] PHP Fatal error:  Call to undefined method MySQLProviderTestModule::getStorageSize() in /home/eval/framework/dataprovider/testsuite/MySQLProviderTestModule.php on line 567
[24-Dec-2013 22:05:04 Europe/Zagreb] PHP Fatal error:  Call to undefined method MySQLProviderTestModule::getStorageSize() in /home/eval/framework/dataprovider/testsuite/MySQLProviderTestModule.php on line 567
[24-Dec-2013 22:07:10 Europe/Zagreb] PHP Warning:  Missing argument 2 for MySQLProvider::getEnum(), called in /home/eval/framework/dataprovider/testsuite/MySQLProviderTestModule.php on line 559 and defined in /home/eval/framework/dataprovider/MySQLProvider.php on line 470
[24-Dec-2013 22:07:10 Europe/Zagreb] PHP Fatal error:  Uncaught exception 'Exception' with message 'Call to undefined method MySQLProvider->tables!' in /home/eval/framework/base/Base.php:226
Stack trace:
#0 /home/eval/framework/dataprovider/MySQLProvider.php(473): Base->__call('tables', Array)
#1 /home/eval/framework/dataprovider/MySQLProvider.php(473): MySQLProvider->tables()
#2 /home/eval/framework/dataprovider/testsuite/MySQLProviderTestModule.php(559): MySQLProvider->getEnum('enum_table')
#3 [internal function]: MySQLProviderTestModule->testGetEnum()
#4 /home/eval/framework/base/TestModule.php(136): call_user_func(Array)
#5 /home/eval/framework/base/TestUnitModule.php(231): TestModule->start()
#6 /home/eval/framework/base/TestUnitModule.php(268): TestUnitModule::runAllTestsOnTestModule('MySQLProviderTe...')
#7 /home/eval/framework/tools/testrun.php(7): TestUnitModule::run(Array)
#8 {main}
  thrown in /home/eval/framework/base/Base.php on line 226
[24-Dec-2013 22:07:28 Europe/Zagreb] PHP Fatal error:  Uncaught exception 'Exception' with message 'Call to undefined method MySQLProvider->tables!' in /home/eval/framework/base/Base.php:226
Stack trace:
#0 /home/eval/framework/dataprovider/MySQLProvider.php(473): Base->__call('tables', Array)
#1 /home/eval/framework/dataprovider/MySQLProvider.php(473): MySQLProvider->tables()
#2 /home/eval/framework/dataprovider/testsuite/MySQLProviderTestModule.php(559): MySQLProvider->getEnum('enum_table', 'enum_val')
#3 [internal function]: MySQLProviderTestModule->testGetEnum()
#4 /home/eval/framework/base/TestModule.php(136): call_user_func(Array)
#5 /home/eval/framework/base/TestUnitModule.php(231): TestModule->start()
#6 /home/eval/framework/base/TestUnitModule.php(268): TestUnitModule::runAllTestsOnTestModule('MySQLProviderTe...')
#7 /home/eval/framework/tools/testrun.php(7): TestUnitModule::run(Array)
#8 {main}
  thrown in /home/eval/framework/base/Base.php on line 226
[24-Dec-2013 22:07:30 Europe/Zagreb] PHP Fatal error:  Uncaught exception 'Exception' with message 'Call to undefined method MySQLProvider->tables!' in /home/eval/framework/base/Base.php:226
Stack trace:
#0 /home/eval/framework/dataprovider/MySQLProvider.php(473): Base->__call('tables', Array)
#1 /home/eval/framework/dataprovider/MySQLProvider.php(473): MySQLProvider->tables()
#2 /home/eval/framework/dataprovider/testsuite/MySQLProviderTestModule.php(559): MySQLProvider->getEnum('enum_table', 'enum_val')
#3 [internal function]: MySQLProviderTestModule->testGetEnum()
#4 /home/eval/framework/base/TestModule.php(136): call_user_func(Array)
#5 /home/eval/framework/base/TestUnitModule.php(231): TestModule->start()
#6 /home/eval/framework/base/TestUnitModule.php(268): TestUnitModule::runAllTestsOnTestModule('MySQLProviderTe...')
#7 /home/eval/framework/tools/testrun.php(7): TestUnitModule::run(Array)
#8 {main}
  thrown in /home/eval/framework/base/Base.php on line 226
[24-Dec-2013 22:07:53 Europe/Zagreb] PHP Warning:  mysql_fetch_array() expects parameter 1 to be resource, object given in /home/eval/framework/dataprovider/MySQLProvider.php on line 476
[24-Dec-2013 22:08:09 Europe/Zagreb] PHP Warning:  mysql_fetch_array() expects parameter 1 to be resource, null given in /home/eval/framework/dataprovider/MySQLProvider.php on line 476
[24-Dec-2013 22:08:40 Europe/Zagreb] PHP Fatal error:  Uncaught exception 'Exception' with message 'Assert Equal failed for array (
  'expected' => 'Duplicate',
  'measured' => false,
)' in /home/eval/framework/base/TestUnitModule.php:191
Stack trace:
#0 /home/eval/framework/dataprovider/testsuite/MysqlPreparedStatementsTestCase.php(148): TestUnitModule->assertEqual('Duplicate', false)
#1 [internal function]: MysqlPreparedStatementsTestCase->preparedStatement_integerArgs_cell()
#2 /home/eval/framework/base/TestUnitModule.php(98): call_user_func(Array)
#3 /home/eval/framework/base/TestUnitModule.php(231): TestUnitModule->start()
#4 /home/eval/framework/base/TestUnitModule.php(268): TestUnitModule::runAllTestsOnTestModule('MysqlPreparedSt...')
#5 /home/eval/framework/tools/testrun.php(7): TestUnitModule::run(Array)
#6 {main}
  thrown in /home/eval/framework/base/TestUnitModule.php on line 191
[24-Dec-2013 22:10:16 Europe/Zagreb] PHP Fatal error:  Uncaught exception 'Exception' with message 'Assert Equal failed for array (
  'expected' => 
  array (
    0 => 'Duplicate',
    1 => 'Duplicate',
  ),
  'measured' => 
  array (
  ),
)' in /home/eval/framework/base/TestUnitModule.php:191
Stack trace:
#0 /home/eval/framework/dataprovider/testsuite/MysqlPreparedStatementsTestCase.php(167): TestUnitModule->assertEqual(Array, Array)
#1 [internal function]: MysqlPreparedStatementsTestCase->preparedStatement_integerArgs_vector()
#2 /home/eval/framework/base/TestUnitModule.php(98): call_user_func(Array)
#3 /home/eval/framework/base/TestUnitModule.php(231): TestUnitModule->start()
#4 /home/eval/framework/base/TestUnitModule.php(268): TestUnitModule::runAllTestsOnTestModule('MysqlPreparedSt...')
#5 /home/eval/framework/tools/testrun.php(7): TestUnitModule::run(Array)
#6 {main}
  thrown in /home/eval/framework/base/TestUnitModule.php on line 191
